### PR TITLE
Fixed opening own feeds, including the assistant, fixes #186

### LINKED ISSUE #186: Opening own feed does not work
Caused by this line:
https://github.com/agazso/postmodern/blob/master/src/containers/FeedContainer.ts#L25

state.ownFeeds is empty until something is shared (the feed is created)

related to #181

### PR DESCRIPTION
**Pull request by agazso**
I'm not completely happy with everything, however as far as I could see everything works, so even if we refactor some things we start from a working state.

Things we can improve:
- Change the AssistantFeed to a LocalFeed -> less special case handling
- NavigationHeaderButton: this already came up when the NavigationHeader was made, to create a component for a button that can has a `text` and `onPress` property. It would improve the readability of the NavigationHeaders.

### CODE REVIEW

File: src/containers/FeedContainer.ts [hunk 1]
```diff
@@ -1,29 +1,44 @@
...
 import { getFeedPosts, getYourPosts } from '../selectors/selectors';
 
 export const mapStateToProps = (state: AppState, ownProps: { navigation: any }): StateProps => {
     const feedUrl = ownProps.navigation.state.params.feedUrl;
-    const selectedFeeds = state.feeds.filter(feed => feed != null && feed.feedUrl === feedUrl);
-    // TODO: we should have here state.ownFeeds.find(feed => feed.url === feedUrl) != null,
-    // but author.uri is empty, and the feedUrl from navparams is from post.author.uri (not real feedUrl)
-    // For the same reason feeds/selectedFeeds is empty (errounously)
-    const isOwnFeed = state.author.uri === feedUrl;
+    const feedName = ownProps.navigation.state.params.name;
```
Comment (vujevits) [inline src/containers/FeedContainer.ts]: params.name could be more specific

File: src/containers/FeedContainer.ts [hunk 2]
```diff
@@ -1,29 +1,44 @@
...
+
+    const isOwnFeed = feedName === state.author.name;
```
Comment (vujevits) [inline src/containers/FeedContainer.ts]: we should store the author name in the feed

Comment (vujevits) [reply src/containers/FeedContainer.ts]: or rather the feed should have an owner

File: src/containers/FeedContainer.ts [hunk 3]
```diff
@@ -1,29 +1,44 @@
...
+    const isAssistantFeed = feedName === 'Felfele Assistant';
+    const hasOwnFeed = state.ownFeeds.length > 0;
+    const ownFeed = hasOwnFeed ? state.ownFeeds[0] : undefined;
+    const selectedFeeds = isOwnFeed
+        ? hasOwnFeed
```
Comment (vujevits) [inline src/containers/FeedContainer.ts]: maybe this would be less ambiguous if we call this variable `isFeedSynchronized` or `isFeedSetUp` or...

File: src/containers/FeedContainer.ts (hunk 2 above)
Comment (agazso) [reply src/containers/FeedContainer.ts]: This is exactly how it is:
- we store the author of the feed in the `name` property of the feed (along with `url` and `feedUrl` properties)
- we have an `author` property in each post indicating the author of the post

File: src/containers/FeedContainer.ts (hunk 1 above)
Comment (agazso) [reply src/containers/FeedContainer.ts]: I didn't want to change this, because passing params through the navigation state is not type safe and I didn't want to introduce other breaking changes.

File: src/containers/FeedContainer.ts (hunk 3 above)
Comment (agazso) [reply src/containers/FeedContainer.ts]: I don't know what feed setup means in the context of the codebase. I know what feed synchronization means in the context of the codebase and it's not what we are trying to express. So to me the suggested names are more ambiguous.

Comment (vujevits) [reply src/containers/FeedContainer.ts]: Yes these are not good either, I was just looking forint the correct wording. hasRemoteCounterpart is a bit long.

File: src/containers/FeedContainer.ts (hunk 2 above)
Comment (vujevits) [reply src/containers/FeedContainer.ts]: By design the idea is that the feedName != authorName

Comment (vujevits) [reply src/containers/FeedContainer.ts]: That's true that we don't support that on the UI
