### PR TITLE
create a view in settings to send bug reports, including logs

### LINKED ISSUE #103: production logging / bug reporting

### PR DESCRIPTION
**Pull request by vujevits**
A simple view in the Settings to send bug reports, including recent log lines.
fixes #103

### CODE REVIEW

File: src/components/LogViewer.tsx [hunk 1]
```diff
@@ -20,6 +20,8 @@ export type Props = StateProps & DispatchProps;
 
 type LogItem = [string, string];
 const logData: LogItem[] = [];
+const BUG_REPORT_EMAIL_ADDRESS = 'mark@felfele.com';
```
Comment (agazso) [inline src/components/LogViewer.tsx]: You might not want to commit your personal address :)

File: src/components/BugReportView.tsx [hunk 2]
```diff
@@ -0,0 +1,52 @@
+import * as React from 'react';
+import { NavigationHeader } from './NavigationHeader';
+import { Colors } from '../styles';
+import Icon from 'react-native-vector-icons/MaterialCommunityIcons';
+import { View, Text, StyleSheet, Linking } from 'react-native';
+import { getBugReportBody } from './LogViewer';
+
+const BUG_REPORT_EMAIL_ADDRESS = 'attila@felfele.com';
```
Comment (agazso) [inline src/components/BugReportView.tsx]: You might not want to commit my personal address :)

**Comment by vujevits** [comment]
Will iterate on design during the general design overhaul.
